# Generated by Django 3.1.1 on 2020-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='text',
            field=models.TextField(default='', max_length=300),
        ),
    ]
